In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv(r"C:\Users\HARISH\OneDrive\Desktop\Global_Ecom_Analytics\3_SQL\data\online_retail_cleaning-2009-2010.csv",encoding='latin1')

C:\Users\HARISH\AppData\Local\Temp\ipykernel_18464\3400100884.py:1: DtypeWarning: Columns (0: Invoice, 1: Transaction_Type, 2: StockCode, 3: Description, 4: InvoiceDate, 5: Customer_Type, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  df1=pd.read_csv(r"C:\Users\HARISH\OneDrive\Desktop\Global_Ecom_Analytics\3_SQL\data\online_retail_cleaning-2009-2010.csv",encoding='latin1')

In [3]:
df2=pd.read_csv(r"C:\Users\HARISH\OneDrive\Desktop\Global_Ecom_Analytics\3_SQL\data\online_retail_cleaning-2010-2011.csv",encoding='latin1')

In [4]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Invoice           518596 non-null  str
 1   Transaction_Type  518596 non-null  str
 2   StockCode         518596 non-null  str
 3   Description       515668 non-null  str
 4   Quantity          518596 non-null  float64
 5   InvoiceDate       518596 non-null  str
 6   Price             518596 non-null  float64
 7   Customer ID       410763 non-null  float64
 8   Customer_Type     518596 non-null  str
 9   Country           518596 non-null  str
dtypes: float64(3), str(7)
memory usage: 40.1 MB

In [5]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Invoice           536642 non-null  str
 1   Transaction_Type  536642 non-null  str
 2   StockCode         536642 non-null  str
 3   Description       535188 non-null  str
 4   Quantity          536642 non-null  float64
 5   InvoiceDate       536642 non-null  str
 6   Price             536642 non-null  float64
 7   Customer ID       401605 non-null  float64
 8   Customer_Type     536642 non-null  str
 9   Country           536642 non-null  str
dtypes: float64(3), str(7)
memory usage: 41.3 MB

In [6]:
df=pd.concat([df1,df2],ignore_index=True)

In [7]:
df.head()

,Invoice,Transaction_Type,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Customer_Type,Country
0,489434,Sale,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12.0,01-12-2009 07:45,6.95,13085.0,REGISTERED,United Kingdom
1,489434,Sale,79323P,PINK CHERRY LIGHTS,12.0,01-12-2009 07:45,6.75,13085.0,REGISTERED,United Kingdom
2,489434,Sale,79323W,WHITE CHERRY LIGHTS,12.0,01-12-2009 07:45,6.75,13085.0,REGISTERED,United Kingdom
3,489434,Sale,22041,"RECORD FRAME 7"" SINGLE SIZE",48.0,01-12-2009 07:45,2.10,13085.0,REGISTERED,United Kingdom
4,489434,Sale,21232,STRAWBERRY CERAMIC TRINKET BOX,24.0,01-12-2009 07:45,1.25,13085.0,REGISTERED,United Kingdom

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 10 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Invoice           1055238 non-null  str
 1   Transaction_Type  1055238 non-null  str
 2   StockCode         1055238 non-null  str
 3   Description       1050856 non-null  str
 4   Quantity          1055238 non-null  float64
 5   InvoiceDate       1055238 non-null  str
 6   Price             1055238 non-null  float64
 7   Customer ID       812368 non-null   float64
 8   Customer_Type     1055238 non-null  str
 9   Country           1055238 non-null  str
dtypes: float64(3), str(7)
memory usage: 81.4 MB

In [9]:
df.describe()

           Quantity         Price    Customer ID
count  1.055238e+06  1.055238e+06  812368.000000
mean   1.002209e+01  4.673714e+00   15317.796570
std    1.736819e+02  1.242609e+02    1698.113489
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13969.000000
50%    3.000000e+00  2.100000e+00   15245.000000
75%    1.000000e+01  4.150000e+00   16794.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [10]:
df.shape

(1067371, 10)

In [11]:
df.columns

Index(['Invoice', 'Transaction_Type', 'StockCode', 'Description', 'Quantity',
       'InvoiceDate', 'Price', 'Customer ID', 'Customer_Type', 'Country'],
      dtype='str')

In [12]:
df.index

RangeIndex(start=0, stop=1067371, step=1)

In [13]:
print("Test")

Test

In [14]:
df.describe()

           Quantity         Price    Customer ID
count  1.055238e+06  1.055238e+06  812368.000000
mean   1.002209e+01  4.673714e+00   15317.796570
std    1.736819e+02  1.242609e+02    1698.113489
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13969.000000
50%    3.000000e+00  2.100000e+00   15245.000000
75%    1.000000e+01  4.150000e+00   16794.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [15]:
df.index

RangeIndex(start=0, stop=1067371, step=1)

In [16]:
df[["Quantity","Price"]].head()

   Quantity  Price
0      12.0   6.95
1      12.0   6.75
2      12.0   6.75
3      48.0   2.10
4      24.0   1.25

In [17]:
quantity = df["Quantity"].to_numpy()
price=df["Price"].to_numpy()

In [19]:
quantity.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [20]:
revenue=quantity*price

In [21]:
revenue[:4]

array([ 83.4,  81. ,  81. , 100.8])

In [24]:
total = np.sum(revenue)

In [25]:
print(total)

nan

In [26]:
np.isnan(revenue).sum()

np.int64(12133)

In [27]:
np.nansum(revenue)

np.float64(19231800.518)

In [29]:
np.isnan(quantity).sum()

np.int64(12133)

In [30]:
np.isnan(price).sum()

np.int64(12133)

In [32]:
df[["Quantity","Price"]].isna().sum()

Quantity    12133
Price       12133
dtype: int64

In [33]:
df[df["Quantity"].isna() & df["Price"].isna()].shape

(12133, 10)

In [34]:
quantity.shape

(1067371,)

In [35]:
quantity.ndim

1

In [36]:
quantity.dtype

dtype('float64')

In [37]:
price.dtype

dtype('float64')

In [38]:
np.sum(quantity)

np.float64(nan)

In [39]:
np.nansum(quantity).sum()

np.float64(10575687.0)

In [41]:
np.mean(quantity)

np.float64(nan)

In [42]:
np.nanmean(quantity)

np.float64(10.022086960477163)

In [43]:
Transaction_Type=np.where(
    quantity>0,
    "Sale",
    "Return"
)

In [44]:
Transaction_Type[:10]

array(['Sale', 'Sale', 'Sale', 'Sale', 'Sale', 'Sale', 'Sale', 'Sale',
       'Sale', 'Sale'], dtype='<U6')

In [45]:
Transaction_Type=="Return"

array([False, False, False, ...,  True,  True,  True], shape=(1067371,))

In [46]:
np.unique(Transaction_Type,return_counts=True)

(array(['Return', 'Sale'], dtype='<U6'), array([  35022, 1032349]))

In [47]:
df["Transaction_Type"]=Transaction_Type

In [48]:
df.columns

Index(['Invoice', 'Transaction_Type', 'StockCode', 'Description', 'Quantity',
       'InvoiceDate', 'Price', 'Customer ID', 'Customer_Type', 'Country'],
      dtype='str')

In [49]:
df["Transaction_Type"].value_counts()

Transaction_Type
Sale      1032349
Return      35022
Name: count, dtype: int64

In [50]:
conditions = [
    quantity>0,
    quantity<0,
    quantity==0
]
choices = [
    "Sale",
    "Return",
    "Zero Quantity"
]

In [51]:
Transaction_Status= np.select(
    conditions,
    choices,
    default="UnKnown"
)

In [53]:
np.unique(Transaction_Status,return_counts=True)

(array(['Return', 'Sale', 'UnKnown'], dtype='<U13'),
 array([  22889, 1032349,   12133]))

In [54]:
np.sum(quantity==0)

np.int64(0)

In [55]:
np.sum(conditions)

np.int64(1055238)

In [56]:
np.sum(quantity<0)

np.int64(22889)

In [57]:
np.nanmean(quantity)

np.float64(10.022086960477163)

In [58]:
np.nanmin(quantity)

np.float64(-80995.0)

In [59]:
np.nanmax(quantity)

np.float64(80995.0)

In [61]:
df[df["Quantity"].isin([-80995,80995])]

,Invoice,Transaction_Type,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Customer_Type,Country
1060621,581483,Sale,23843,"PAPER CRAFT , LITTLE BIRDIE",80995.0,09-12-2011 09:15,2.08,16446.0,REGISTERED,United Kingdom
1060622,C581484,Return,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995.0,09-12-2011 09:27,2.08,16446.0,REGISTERED,United Kingdom

In [62]:
np.nanstd(quantity)

np.float64(173.6818228253457)

In [65]:
np.sum(quantity<0)

np.int64(22889)

In [66]:
np.sum(quantity[quantity<0])

np.float64(-1061934.0)

In [67]:
abs(np.sum(quantity[quantity<0]))

np.float64(1061934.0)

In [68]:
np.unique(df["Country"].to_numpy())

TypeError: '<' not supported between instances of 'float' and 'str'

In [69]:
np.unique(df["Country"].to_numpy())

TypeError: '<' not supported between instances of 'float' and 'str'

In [70]:
df["Country"].dtype

In [71]:
country=df["Country"].to_numpy(dtype=object)

In [72]:
np.unique(country)

TypeError: '<' not supported between instances of 'float' and 'str'

In [73]:
country=df["Country"].dropna().to_numpy()

In [ ]:
np.unique(country)

array(['Australia', 'Austria', 'Bahrain', 'Belgium', 'Bermuda', 'Brazil',
       'Canada', 'Channel Islands', 'Cyprus', 'Czech Republic', 'Denmark',
       'EIRE', 'European Community', 'Finland', 'France', 'Germany',
       'Greece', 'Hong Kong', 'Iceland', 'Israel', 'Italy', 'Japan',
       'Korea', 'Lebanon', 'Lithuania', 'Malta', 'Netherlands', 'Nigeria',
       'Norway', 'Poland', 'Portugal', 'RSA', 'Saudi Arabia', 'Singapore',
       'Spain', 'Sweden', 'Switzerland', 'Thailand', 'USA',
       'United Arab Emirates', 'United Kingdom', 'Unspecified',
       'West Indies'], dtype=object)

In [77]:
np.unique(country)

array(['Australia', 'Austria', 'Bahrain', 'Belgium', 'Bermuda', 'Brazil',
       'Canada', 'Channel Islands', 'Cyprus', 'Czech Republic', 'Denmark',
       'EIRE', 'European Community', 'Finland', 'France', 'Germany',
       'Greece', 'Hong Kong', 'Iceland', 'Israel', 'Italy', 'Japan',
       'Korea', 'Lebanon', 'Lithuania', 'Malta', 'Netherlands', 'Nigeria',
       'Norway', 'Poland', 'Portugal', 'RSA', 'Saudi Arabia', 'Singapore',
       'Spain', 'Sweden', 'Switzerland', 'Thailand', 'USA',
       'United Arab Emirates', 'United Kingdom', 'Unspecified',
       'West Indies'], dtype=object)

In [78]:
len(np.unique(country))

43

In [79]:
np.unique(country,return_counts=True)

(array(['Australia', 'Austria', 'Bahrain', 'Belgium', 'Bermuda', 'Brazil',
        'Canada', 'Channel Islands', 'Cyprus', 'Czech Republic', 'Denmark',
        'EIRE', 'European Community', 'Finland', 'France', 'Germany',
        'Greece', 'Hong Kong', 'Iceland', 'Israel', 'Italy', 'Japan',
        'Korea', 'Lebanon', 'Lithuania', 'Malta', 'Netherlands', 'Nigeria',
        'Norway', 'Poland', 'Portugal', 'RSA', 'Saudi Arabia', 'Singapore',
        'Spain', 'Sweden', 'Switzerland', 'Thailand', 'USA',
        'United Arab Emirates', 'United Kingdom', 'Unspecified',
        'West Indies'], dtype=object),
 array([  1912,    938,    126,   3122,     34,     94,    228,   1663,
          1157,     30,    817,  17844,     61,   1049,  14296,  17600,
           663,    360,    253,    368,   1532,    582,     63,     58,
           189,    299,   5139,     32,   1455,    535,   2608,    169,
            10,    346,   3799,   1362,   3181,     76,    535,    500,
        969347,    752,     54]))